import { EmployeeType } from "../types";

export const mockedEmployees: object[] = [
  {
    firstname: "1AAAA",
    lastname: "RXXXXXXXXXXX",
    startdate: "01/01/01",
    department: "ZXXXXXXXXXXX",
    birthdate: "01/01/01",
    street: "AXXXXXXXXXXX",
    city: "VXXXXXXXXXXX",
    state: "XXXXXXXXXXX",
    zipcode: "800000",
  },
  {
    firstname: "2BBBB",
    lastname: "AXXXXXXXXXXX",
    startdate: "01/01/01",
    department: "CXXXXXXXXXXX",
    birthdate: "01/01/01",
    street: "UXXXXXXXXXXX",
    city: "OXXXXXXXXXXX",
    state: "YXXXXXXXXXXX",
    zipcode: "100000",
  },
  {
    firstname: "3CCCC",
    lastname: "XXXXXXXXXXX",
    startdate: "01/01/01",
    department: "XXXXXXXXXXX",
    birthdate: "01/01/01",
    street: "XXXXXXXXXXX",
    city: "XXXXXXXXXXX",
    state: "XXXXXXXXXXX",
    zipcode: "900000",
  },
  {
    firstname: "4CCCCC",
    lastname: "XXXXXXXXXXX",
    startdate: "01/01/01",
    department: "XXXXXXXXXXX",
    birthdate: "01/01/01",
    street: "XXXXXXXXXXX",
    city: "XXXXXXXXXXX",
    state: "XXXXXXXXXXX",
    zipcode: "100000",
  },
  {
    firstname: "5DDDDD",
    lastname: "FXXXXXXXXXX",
    startdate: "01/01/01",
    department: "KXXXXXXXXXX",
    birthdate: "01/01/01",
    street: "MXXXXXXXXXX",
    city: "JXXXXXXXXXX",
    state: "EXXXXXXXXXX",
    zipcode: "000000",
  },
  {
    firstname: "6EEEEEE",
    lastname: "XXXXXXXXXXX",
    startdate: "04/01/03",
    department: "VXXXXXXXXXX",
    birthdate: "01/01/10",
    street: "VXXXXXXXXX",
    city: "EXXXXXXXXXXX",
    state: "EXXXXXXXXXXX",
    zipcode: "000000",
  },
  {
    firstname: "7FFFFFF",
    lastname: "XXXXXXXXXXX",
    startdate: "01/01/04",
    department: "XXXXXXXXXXX",
    birthdate: "01/01/02",
    street: "XXXXXXXXXXX",
    city: "XXXXXXXXXXX",
    state: "XXXXXXXXXXX",
    zipcode: "000000",
  },
  {
    firstname: "8AAAA",
    lastname: "XXXXXXXXXXX",
    startdate: "02/01/01",
    department: "XXXXXXXXXXX",
    birthdate: "014/01/01",
    street: "XXXXXXXXXXX",
    city: "XXXXXXXXXXX",
    state: "XXXXXXXXXXX",
    zipcode: "000000",
  },
  {
    firstname: "9BBBB",
    lastname: "XXXXXXXXXXX",
    startdate: "05/10/01",
    department: "XXXXXXXXXXX",
    birthdate: "01/01/01",
    street: "XXXXXXXXXXX",
    city: "XXXXXXXXXXX",
    state: "XXXXXXXXXXX",
    zipcode: "000000",
  },
  {
    firstname: "10CCCC",
    lastname: "XXXXXXXXXXX",
    startdate: "09/11/01",
    department: "XXXXXXXXXXX",
    birthdate: "01/01/01",
    street: "XXXXXXXXXXX",
    city: "XXXXXXXXXXX",
    state: "XXXXXXXXXXX",
    zipcode: "000000",
  },
  {
    firstname: "11CCCCC",
    lastname: "XXXXXXXXXXX",
    startdate: "01/01/01",
    department: "XXXXXXXXXXX",
    birthdate: "01/01/01",
    street: "XXXXXXXXXXX",
    city: "XXXXXXXXXXX",
    state: "XXXXXXXXXXX",
    zipcode: "000000",
  },
  {
    firstname: "12DDDDD",
    lastname: "XXXXXXXXXXX",
    startdate: "01/01/01",
    department: "XXXXXXXXXXX",
    birthdate: "01/01/01",
    street: "XXXXXXXXXXX",
    city: "XXXXXXXXXXX",
    state: "XXXXXXXXXXX",
    zipcode: "000000",
  },
  {
    firstname: "13EEEEEE",
    lastname: "XXXXXXXXXXX",
    startdate: "01/01/01",
    department: "XXXXXXXXXXX",
    birthdate: "01/01/01",
    street: "XXXXXXXXXXX",
    city: "XXXXXXXXXXX",
    state: "XXXXXXXXXXX",
    zipcode: "000000",
  },
  {
    firstname: "14FFFFFF",
    lastname: "XXXXXXXXXXX",
    startdate: "01/01/01",
    department: "XXXXXXXXXXX",
    birthdate: "01/01/01",
    street: "XXXXXXXXXXX",
    city: "XXXXXXXXXXX",
    state: "XXXXXXXXXXX",
    zipcode: "000000",
  },
  {
    firstname: "15AAAA",
    lastname: "XXXXXXXXXXX",
    startdate: "01/01/01",
    department: "XXXXXXXXXXX",
    birthdate: "01/01/01",
    street: "XXXXXXXXXXX",
    city: "XXXXXXXXXXX",
    state: "XXXXXXXXXXX",
    zipcode: "000000",
  },
  {
    firstname: "16BBBB",
    lastname: "XXXXXXXXXXX",
    startdate: "01/01/01",
    department: "XXXXXXXXXXX",
    birthdate: "01/01/01",
    street: "XXXXXXXXXXX",
    city: "XXXXXXXXXXX",
    state: "XXXXXXXXXXX",
    zipcode: "000000",
  },
  {
    firstname: "17CCCC",
    lastname: "XXXXXXXXXXX",
    startdate: "01/01/01",
    department: "XXXXXXXXXXX",
    birthdate: "01/01/01",
    street: "XXXXXXXXXXX",
    city: "XXXXXXXXXXX",
    state: "XXXXXXXXXXX",
    zipcode: "000000",
  },
  {
    firstname: "18CCCC",
    lastname: "XXXXXXXXXXX",
    startdate: "01/01/01",
    department: "XXXXXXXXXXX",
    birthdate: "01/01/01",
    street: "XXXXXXXXXXX",
    city: "XXXXXXXXXXX",
    state: "XXXXXXXXXXX",
    zipcode: "000000",
  },
  {
    firstname: "19CCCCC",
    lastname: "XXXXXXXXXXX",
    startdate: "01/01/01",
    department: "XXXXXXXXXXX",
    birthdate: "01/01/01",
    street: "XXXXXXXXXXX",
    city: "XXXXXXXXXXX",
    state: "XXXXXXXXXXX",
    zipcode: "000000",
  },
  {
    firstname: "20DDDDD",
    lastname: "XXXXXXXXXXX",
    startdate: "01/01/01",
    department: "XXXXXXXXXXX",
    birthdate: "01/01/01",
    street: "XXXXXXXXXXX",
    city: "XXXXXXXXXXX",
    state: "XXXXXXXXXXX",
    zipcode: "000000",
  },
  {
    firstname: "21EEEEEE",
    lastname: "XXXXXXXXXXX",
    startdate: "01/01/01",
    department: "XXXXXXXXXXX",
    birthdate: "01/01/01",
    street: "XXXXXXXXXXX",
    city: "XXXXXXXXXXX",
    state: "XXXXXXXXXXX",
    zipcode: "000000",
  },
  {
    firstname: "22FFFFFF",
    lastname: "XXXXXXXXXXX",
    startdate: "01/01/01",
    department: "XXXXXXXXXXX",
    birthdate: "01/01/01",
    street: "XXXXXXXXXXX",
    city: "XXXXXXXXXXX",
    state: "XXXXXXXXXXX",
    zipcode: "000000",
  },
  {
    firstname: "23AAAA",
    lastname: "XXXXXXXXXXX",
    startdate: "01/01/01",
    department: "XXXXXXXXXXX",
    birthdate: "01/01/01",
    street: "XXXXXXXXXXX",
    city: "XXXXXXXXXXX",
    state: "XXXXXXXXXXX",
    zipcode: "000000",
  },
  {
    firstname: "24BBBB",
    lastname: "XXXXXXXXXXX",
    startdate: "01/01/01",
    department: "XXXXXXXXXXX",
    birthdate: "01/01/01",
    street: "XXXXXXXXXXX",
    city: "XXXXXXXXXXX",
    state: "XXXXXXXXXXX",
    zipcode: "000000",
  },
  {
    firstname: "25CCCC",
    lastname: "XXXXXXXXXXX",
    startdate: "01/01/01",
    department: "XXXXXXXXXXX",
    birthdate: "01/01/01",
    street: "XXXXXXXXXXX",
    city: "XXXXXXXXXXX",
    state: "XXXXXXXXXXX",
    zipcode: "000000",
  },
  {
    firstname: "26CCCCC",
    lastname: "XXXXXXXXXXX",
    startdate: "01/01/01",
    department: "XXXXXXXXXXX",
    birthdate: "01/01/01",
    street: "XXXXXXXXXXX",
    city: "XXXXXXXXXXX",
    state: "XXXXXXXXXXX",
    zipcode: "000000",
  },
  {
    firstname: "27DDDDD",
    lastname: "XXXXXXXXXXX",
    startdate: "01/01/01",
    department: "XXXXXXXXXXX",
    birthdate: "01/01/01",
    street: "XXXXXXXXXXX",
    city: "XXXXXXXXXXX",
    state: "XXXXXXXXXXX",
    zipcode: "000000",
  },
  {
    firstname: "28EEEEEE",
    lastname: "XXXXXXXXXXX",
    startdate: "01/01/01",
    department: "XXXXXXXXXXX",
    birthdate: "01/01/01",
    street: "XXXXXXXXXXX",
    city: "XXXXXXXXXXX",
    state: "XXXXXXXXXXX",
    zipcode: "000000",
  },
  {
    firstname: "29FFFFFF",
    lastname: "XXXXXXXXXXX",
    startdate: "01/01/01",
    department: "XXXXXXXXXXX",
    birthdate: "01/01/01",
    street: "XXXXXXXXXXX",
    city: "XXXXXXXXXXX",
    state: "XXXXXXXXXXX",
    zipcode: "000000",
  },
  {
    firstname: "30AAAA",
    lastname: "XXXXXXXXXXX",
    startdate: "01/01/01",
    department: "XXXXXXXXXXX",
    birthdate: "01/01/01",
    street: "XXXXXXXXXXX",
    city: "XXXXXXXXXXX",
    state: "XXXXXXXXXXX",
    zipcode: "000000",
  },
  {
    firstname: "31BBBB",
    lastname: "XXXXXXXXXXX",
    startdate: "01/01/01",
    department: "XXXXXXXXXXX",
    birthdate: "01/01/01",
    street: "XXXXXXXXXXX",
    city: "XXXXXXXXXXX",
    state: "XXXXXXXXXXX",
    zipcode: "000000",
  },
  {
    firstname: "32CCCC",
    lastname: "XXXXXXXXXXX",
    startdate: "01/01/01",
    department: "XXXXXXXXXXX",
    birthdate: "01/01/01",
    street: "XXXXXXXXXXX",
    city: "XXXXXXXXXXX",
    state: "XXXXXXXXXXX",
    zipcode: "000000",
  },
  {
    firstname: "33CCCCC",
    lastname: "XXXXXXXXXXX",
    startdate: "01/01/01",
    department: "XXXXXXXXXXX",
    birthdate: "01/01/01",
    street: "XXXXXXXXXXX",
    city: "XXXXXXXXXXX",
    state: "XXXXXXXXXXX",
    zipcode: "000000",
  },
  {
    firstname: "34DDDDD",
    lastname: "XXXXXXXXXXX",
    startdate: "01/01/01",
    department: "XXXXXXXXXXX",
    birthdate: "01/01/01",
    street: "XXXXXXXXXXX",
    city: "XXXXXXXXXXX",
    state: "XXXXXXXXXXX",
    zipcode: "000000",
  },
  {
    firstname: "35EEEEEE",
    lastname: "XXXXXXXXXXX",
    startdate: "01/01/01",
    department: "XXXXXXXXXXX",
    birthdate: "01/01/01",
    street: "XXXXXXXXXXX",
    city: "XXXXXXXXXXX",
    state: "XXXXXXXXXXX",
    zipcode: "000000",
  },
  {
    firstname: "36FFFFFF",
    lastname: "XXXXXXXXXXX",
    startdate: "01/01/01",
    department: "XXXXXXXXXXX",
    birthdate: "01/01/01",
    street: "XXXXXXXXXXX",
    city: "XXXXXXXXXXX",
    state: "XXXXXXXXXXX",
    zipcode: "000000",
  },
  {
    firstname: "37AAAA",
    lastname: "XXXXXXXXXXX",
    startdate: "01/01/01",
    department: "XXXXXXXXXXX",
    birthdate: "01/01/01",
    street: "XXXXXXXXXXX",
    city: "XXXXXXXXXXX",
    state: "XXXXXXXXXXX",
    zipcode: "000000",
  },
  {
    firstname: "38BBBB",
    lastname: "XXXXXXXXXXX",
    startdate: "01/01/01",
    department: "XXXXXXXXXXX",
    birthdate: "01/01/01",
    street: "XXXXXXXXXXX",
    city: "XXXXXXXXXXX",
    state: "XXXXXXXXXXX",
    zipcode: "000000",
  },
  {
    firstname: "39CCCC",
    lastname: "XXXXXXXXXXX",
    startdate: "01/01/01",
    department: "XXXXXXXXXXX",
    birthdate: "01/01/01",
    street: "XXXXXXXXXXX",
    city: "XXXXXXXXXXX",
    state: "XXXXXXXXXXX",
    zipcode: "000000",
  },
  {
    firstname: "40CCCCC",
    lastname: "XXXXXXXXXXX",
    startdate: "01/01/01",
    department: "XXXXXXXXXXX",
    birthdate: "01/01/01",
    street: "XXXXXXXXXXX",
    city: "XXXXXXXXXXX",
    state: "XXXXXXXXXXX",
    zipcode: "000000",
  },
  {
    firstname: "41DDDDD",
    lastname: "XXXXXXXXXXX",
    startdate: "01/01/01",
    department: "XXXXXXXXXXX",
    birthdate: "01/01/01",
    street: "XXXXXXXXXXX",
    city: "XXXXXXXXXXX",
    state: "XXXXXXXXXXX",
    zipcode: "000000",
  },
  {
    firstname: "42EEEEEE",
    lastname: "XXXXXXXXXXX",
    startdate: "01/01/01",
    department: "XXXXXXXXXXX",
    birthdate: "01/01/01",
    street: "XXXXXXXXXXX",
    city: "XXXXXXXXXXX",
    state: "XXXXXXXXXXX",
    zipcode: "000000",
  },
  {
    firstname: "43FFFFFF",
    lastname: "XXXXXXXXXXX",
    startdate: "01/01/01",
    department: "XXXXXXXXXXX",
    birthdate: "01/01/01",
    street: "XXXXXXXXXXX",
    city: "XXXXXXXXXXX",
    state: "XXXXXXXXXXX",
    zipcode: "000000",
  },
  {
    firstname: "44AAAA",
    lastname: "XXXXXXXXXXX",
    startdate: "01/01/01",
    department: "XXXXXXXXXXX",
    birthdate: "01/01/01",
    street: "XXXXXXXXXXX",
    city: "XXXXXXXXXXX",
    state: "XXXXXXXXXXX",
    zipcode: "000000",
  },
  {
    firstname: "45BBBB",
    lastname: "XXXXXXXXXXX",
    startdate: "01/01/01",
    department: "XXXXXXXXXXX",
    birthdate: "01/01/01",
    street: "XXXXXXXXXXX",
    city: "XXXXXXXXXXX",
    state: "XXXXXXXXXXX",
    zipcode: "000000",
  },
  {
    firstname: "46CCCC",
    lastname: "XXXXXXXXXXX",
    startdate: "01/01/01",
    department: "XXXXXXXXXXX",
    birthdate: "01/01/01",
    street: "XXXXXXXXXXX",
    city: "XXXXXXXXXXX",
    state: "XXXXXXXXXXX",
    zipcode: "000000",
  },
  {
    firstname: "47CCCCC",
    lastname: "XXXXXXXXXXX",
    startdate: "01/01/01",
    department: "XXXXXXXXXXX",
    birthdate: "01/01/01",
    street: "XXXXXXXXXXX",
    city: "XXXXXXXXXXX",
    state: "XXXXXXXXXXX",
    zipcode: "000000",
  },
  {
    firstname: "48DDDDD",
    lastname: "XXXXXXXXXXX",
    startdate: "01/01/01",
    department: "XXXXXXXXXXX",
    birthdate: "01/01/01",
    street: "XXXXXXXXXXX",
    city: "XXXXXXXXXXX",
    state: "XXXXXXXXXXX",
    zipcode: "000000",
  },
  {
    firstname: "49EEEEEE",
    lastname: "XXXXXXXXXXX",
    startdate: "01/01/01",
    department: "XXXXXXXXXXX",
    birthdate: "01/01/01",
    street: "XXXXXXXXXXX",
    city: "XXXXXXXXXXX",
    state: "XXXXXXXXXXX",
    zipcode: "000000",
  },
  {
    firstname: "50FFFFFF",
    lastname: "XXXXXXXXXXX",
    startdate: "01/01/01",
    department: "XXXXXXXXXXX",
    birthdate: "01/01/01",
    street: "XXXXXXXXXXX",
    city: "XXXXXXXXXXX",
    state: "XXXXXXXXXXX",
    zipcode: "000000",
  },
  {
    firstname: "51AAAA",
    lastname: "XXXXXXXXXXX",
    startdate: "01/01/01",
    department: "XXXXXXXXXXX",
    birthdate: "01/01/01",
    street: "XXXXXXXXXXX",
    city: "XXXXXXXXXXX",
    state: "XXXXXXXXXXX",
    zipcode: "000000",
  },
  {
    firstname: "52BBBB",
    lastname: "XXXXXXXXXXX",
    startdate: "01/01/01",
    department: "XXXXXXXXXXX",
    birthdate: "01/01/01",
    street: "XXXXXXXXXXX",
    city: "XXXXXXXXXXX",
    state: "XXXXXXXXXXX",
    zipcode: "000000",
  },
  {
    firstname: "53CCCC",
    lastname: "XXXXXXXXXXX",
    startdate: "01/01/01",
    department: "XXXXXXXXXXX",
    birthdate: "01/01/01",
    street: "XXXXXXXXXXX",
    city: "XXXXXXXXXXX",
    state: "XXXXXXXXXXX",
    zipcode: "000000",
  },
  {
    firstname: "54CCCCC",
    lastname: "XXXXXXXXXXX",
    startdate: "01/01/01",
    department: "XXXXXXXXXXX",
    birthdate: "01/01/01",
    street: "XXXXXXXXXXX",
    city: "XXXXXXXXXXX",
    state: "XXXXXXXXXXX",
    zipcode: "000000",
  },
  {
    firstname: "55DDDDD",
    lastname: "XXXXXXXXXXX",
    startdate: "01/01/01",
    department: "XXXXXXXXXXX",
    birthdate: "01/01/01",
    street: "XXXXXXXXXXX",
    city: "XXXXXXXXXXX",
    state: "XXXXXXXXXXX",
    zipcode: "000000",
  },
  {
    firstname: "56EEEEEE",
    lastname: "XXXXXXXXXXX",
    startdate: "01/01/01",
    department: "XXXXXXXXXXX",
    birthdate: "01/01/01",
    street: "XXXXXXXXXXX",
    city: "XXXXXXXXXXX",
    state: "XXXXXXXXXXX",
    zipcode: "000000",
  },
  {
    firstname: "57FFFFFF",
    lastname: "XXXXXXXXXXX",
    startdate: "01/01/01",
    department: "XXXXXXXXXXX",
    birthdate: "01/01/01",
    street: "XXXXXXXXXXX",
    city: "XXXXXXXXXXX",
    state: "XXXXXXXXXXX",
    zipcode: "000000",
  },
];
