import { EmployeeType } from "../types";

export const mockedEmployees: EmployeeType[] = [
  {
    firstname: "AAAA",
    lastname: "XXXXXXXXXXX",
    startdate: "01/01/01",
    department: "XXXXXXXXXXX",
    birthdate: "01/01/01",
    street: "XXXXXXXXXXX",
    city: "XXXXXXXXXXX",
    state: "XXXXXXXXXXX",
    zipcode: "000000",
  },
  {
    firstname: "BBBB",
    lastname: "XXXXXXXXXXX",
    startdate: "01/01/01",
    department: "XXXXXXXXXXX",
    birthdate: "01/01/01",
    street: "XXXXXXXXXXX",
    city: "XXXXXXXXXXX",
    state: "XXXXXXXXXXX",
    zipcode: "000000",
  },
  {
    firstname: "CCCC",
    lastname: "XXXXXXXXXXX",
    startdate: "01/01/01",
    department: "XXXXXXXXXXX",
    birthdate: "01/01/01",
    street: "XXXXXXXXXXX",
    city: "XXXXXXXXXXX",
    state: "XXXXXXXXXXX",
    zipcode: "000000",
  },
  {
    firstname: "CCCCC",
    lastname: "XXXXXXXXXXX",
    startdate: "01/01/01",
    department: "XXXXXXXXXXX",
    birthdate: "01/01/01",
    street: "XXXXXXXXXXX",
    city: "XXXXXXXXXXX",
    state: "XXXXXXXXXXX",
    zipcode: "000000",
  },
  {
    firstname: "DDDDD",
    lastname: "XXXXXXXXXXX",
    startdate: "01/01/01",
    department: "XXXXXXXXXXX",
    birthdate: "01/01/01",
    street: "XXXXXXXXXXX",
    city: "XXXXXXXXXXX",
    state: "XXXXXXXXXXX",
    zipcode: "000000",
  },
  {
    firstname: "EEEEEE",
    lastname: "XXXXXXXXXXX",
    startdate: "01/01/01",
    department: "XXXXXXXXXXX",
    birthdate: "01/01/01",
    street: "XXXXXXXXXXX",
    city: "XXXXXXXXXXX",
    state: "XXXXXXXXXXX",
    zipcode: "000000",
  },
  {
    firstname: "FFFFFF",
    lastname: "XXXXXXXXXXX",
    startdate: "01/01/01",
    department: "XXXXXXXXXXX",
    birthdate: "01/01/01",
    street: "XXXXXXXXXXX",
    city: "XXXXXXXXXXX",
    state: "XXXXXXXXXXX",
    zipcode: "000000",
  },
];
